document.addEventListener("DOMContentLoaded",function(){
  $("#navigater").load("/src/html/navi.html",function(){
    $("#version").load("/version");
  });
  $("#blog").load("/src/html/blog.html",function(){
    $("#achive1").load("/src/html/blog/achive1.html",function(){
      self.Prism.fileHighlight();
    });
    self.Prism.highlightAll();
  });
});